#!/bin/bash
set -x

if [ -e "$(dirname $0)/common.sh" ]; then
    source $(dirname $0)/common.sh
elif [ -e "$(dirname $0)/../common/common.sh" ]; then
    source $(dirname $0)/../common/common.sh
fi

init()
{
    print_not_supported
}

create()
{
    print_not_supported
}

delete()
{
    print_not_supported
}

get_attached_dev()
{
    print_not_supported
}

attach()
{
    print_not_supported
}

detach()
{
    print_not_supported
}

mountdest()
{
    print_not_supported
}

unmount()
{
    print_not_supported
}

# Every script must call main as such
main "$@"
